name: "build-and-deploy"
on:
  push:
    paths:
      - 'docker-compose.yml'
      - 'image/**'
      - 'extensions.txt'
      - '.github/workflows/vcsToComposer.yaml'
permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  actions: write
  pages: write
jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Satis container
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_REPOSITORY: ${{  github.repository }}
        run: docker-compose up
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main
      - name: push artifact
        run: |
          cd ./html
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "My git repo html"
          git push